
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

development:
  <<: *default
  database: resize_with_sidekiq_development

 
test:
  <<: *default
  database: resize_with_sidekiq_test

production:
  <<: *default
  database: resize_with_sidekiq_production
  username: resize_with_sidekiq
  password: <%= ENV['RESIZE_WITH_SIDEKIQ_DATABASE_PASSWORD'] %>
